ALTER TABLE rooms
    ADD COLUMN IF NOT EXISTS dest_lat DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS dest_lng DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS dest_set_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS dest_set_by UUID REFERENCES users (id);

DROP TABLE IF EXISTS waypoints;
